export const START_GET_MESSAGES = "START_GET_MESSAGES";
export const SUCCESS_GET_MESSAGES = "SUCCESS_GET_MESSAGES";

export const START_GET_USERS = "START_GET_USERS";
export const SUCCESS_GET_USERS = "SUCCESS_GET_USERS";

export const START_GET_ACCOUNT = "START_GET_ACCOUNT";
export const SUCCESS_GET_ACCOUNT = "SUCCESS_GET_ACCOUNT";

export const START_TOKEN_CHECK = "START_TOKEN_CHECK";
export const SUCCESS_TOKEN_CHECK = "SUCCESS_TOKEN_CHECK";
export const FAILED_TOKEN_CHECK = "FAILED_TOKEN_CHECK";

export const START_ADD_USER = "START_ADD_USER";
export const SUCCESS_ADD_USER = "SUCCESS_ADD_USER";

export const START_DELETE_USER = "START_DELETE_USER";
export const SUCCESS_DELETE_USER = "SUCCESS_DELETE_USER";

export const START_SEND_MESSAGE = "START_SEND_MESSAGE";
export const SUCCESS_SEND_MESSAGE = "SUCCESS_SEND_MESSAGE";

export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const FAILED_REGISTER = "FAILED_REGISTER";

export const FAILED_LOGIN = "FAILED_LOGIN";